### ISSUE TITLE
Refactor Version Constraints

### ISSUE THREAD

**Issue by lshpaner** [uclamii/model_tuner#43]
## Refactor Version Constraints in `setup.py` to Ensure Flexibility and Stability

Currently, the version constraints in the `setup.py` file use a mix of minimum version specifiers (e.g., `>=`) for the dependencies. While this provides flexibility in allowing newer versions of libraries, it may also introduce compatibility issues if future versions of dependencies introduce breaking changes.

The `setup.py` file contains version constraints using the `>=` specifier, which allows the installation of newer versions without any upper bounds.

### Proposed Refactor (Example)

```python
install_requires=[
    "joblib>=1.3.2,<2.0.0",
    "numpy>=1.21.6,<2.0.0",
    "pandas>=1.3.5,<2.0.0",
    "scikit-learn>=1.0.2,<2.0.0",
    "scipy>=1.7.3,<2.0.0",
    "tqdm>=4.66.4,<5.0.0",
],
```

Currently tested on:

- `python 3.7` ---> `catboosttest.py`

This ensures that the project remains compatible with future releases of these libraries but avoids breaking changes that may come with major version upgrades (i.e., `2.0.0` or later).

Benefits of Refactoring:

- Improves stability by preventing breaking changes from major version releases.
- Ensures that the project maintains compatibility with a tested range of dependency versions.
- Offers a balance between flexibility (using newer minor/patch updates) and stability (avoiding potentially breaking major versions).

This refactor will help prevent unexpected behavior in production and improve the long-term maintainability of the project.

**Comment by elemets** [comment]
We've completed this for the new bayesian addition as well as for different python versions 3.7-3.11
