### ISSUE TITLE
N_Jobs Not Usable Input

### ISSUE THREAD

**Issue by lshpaner** [uclamii/model_tuner#49]
Currently, as it stands, the `n_jobs` input inside the `Model` class does not produce sound and proper parallelization of the cpu cores. 

- Instead, we must rely on including this as a hyperparameter inside the model's function call. 
- This works, but creates an additional hyperparameter for the `GridSearch` to search through, which in and of itself may slow down the iterative process in general. 

Perhaps, there is a way for us to fix this such that it works by passing it as an input inside `Model()`.

**Comment by elemets** [comment]
Example added in tutorial. `n_jobs` defined in model definition.
