### ISSUE TITLE
RFE use

### ISSUE THREAD

**Issue by panas89** [uclamii/model_tuner#56]
When using RFE (for tutorials and documentation): the estimator used by RFE

1. Either tune it in the grid search (costly)
2. Use a low complexity model with high regularization (e.g., ElasticNet, Logistic regression)

**Comment by elemets** [comment]
Updated in test files still needs to be updated in the documentation

**Comment by elemets** [comment]
Put RFE in an example on colab.

**Comment by lshpaner** [comment]
Done for colab:

https://colab.research.google.com/drive/12XywbGBiwlZIbi0C3JKu9NOQPPRgVwcp#scrollTo=63cGFf6xT9vz

Done for documentation:

https://uclamii.github.io/model_tuner/usage_guide.html#recursive-feature-elimination-rfe
