### ISSUE TITLE
Warning: Parameters { "device", "verbose" } might not be used

### ISSUE THREAD

**Issue by lshpaner** [uclamii/model_tuner#74]
## Description
A warning has been encountered while using `XGBoost`, stating that some parameters might not be used. Here is a snippet of the looped warning output:

```python
[10:32:56] WARNING: ../src/learner.cc:627: 
Parameters: { "device", "verbose" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.
```

### Expected Behavior
The parameters should either be used as expected or flagged correctly to avoid unnecessary warnings.

Additional Context: This warning appears in `learner.cc` and may indicate that some parameters are used in certain bindings but not fully recognized in the XGBoost core. Please clarify if these parameters (`"device", "verbose"`) are supported, and if not, whether they should be removed from the parameter list to prevent this warning.

**Comment by elemets** [comment]
A fix for this will be released in 0.17a.
