### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by elemets** [uclamii/model_tuner#8]
- [ ] Binary classification:
- [ ] Logistic Regression
- [ ] XGBoost with early stopping
- [ ] KFold
- [ ] Regression:
- [ ] Lasso
- [ ] XGBRegressor with early stopping
- [ ] Kfold
- [ ] Multi label:
- [ ] Random Forests

**Comment by lshpaner** [comment]
Documentation exists:

https://uclamii.github.io/model_tuner/
